spring:
  mail:
    host: smtp.163.com
    username: xxx@163.com
    password: xxx
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          socketFactory:
            port: 465
          ssl:
            trust: smtp.163.com
